#ifndef _ACCRQA_DEFINITIONS_DEF
#define _ACCRQA_DEFINITIONS_DEF

#include <stdio.h>

//#define MONITOR_PERFORMANCE

#define ACCRQA_METRIC_EUCLIDEAN 1
#define ACCRQA_METRIC_MAXIMAL 2

#define ACCRQA_SUCCESS 0
#define ACCRQA_ERROR_CUDA_NOT_FOUND 1
#define ACCRQA_ERROR_WRONG_ARGUMENTS 2
#define ACCRQA_ERROR_ARRAYS_NOT_ALLOCATED 3
#define ACCRQA_ERROR_WRONG_METRIC_TYPE 4
#define ACCRQA_ERROR_CUDA_DEVICE_NOT_FOUND 5
#define ACCRQA_ERROR_CUDA_NOT_ENOUGH_MEMORY 6
#define ACCRQA_ERROR_CUDA_MEMORY_ALLOCATION 7
#define ACCRQA_ERROR_CUDA_MEMORY_COPY 8
#define ACCRQA_ERROR_CUDA_KERNEL 9

#endif