name: Generate Sphinx documentation

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
        
      - name: Install dependencies
        run: sudo apt-get install -y doxygen graphviz
          && pip3 install sphinx
          && pip3 install sphinx-rtd-theme
          && pip3 install breathe
          && pip3 install sphinx-sitemap

      - name: Build Sphinx documentation
        run: cd docs
          && make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh-pages
